# Generated by Django 5.2.4 on 2025-07-21 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_productestablishment_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productestablishment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_sightings', to=settings.AUTH_USER_MODEL),
        ),
    ]
