# Generated by Django 5.2.4 on 2025-07-21 18:35

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_productestablishment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='places_esta_search__be54a6_gin'),
        ),
    ]
